// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeAudioDevice(arg1, arg2) {
  return window['go']['main']['App']['ChangeAudioDevice'](arg1, arg2);
}

export function GetAudioInputs() {
  return window['go']['main']['App']['GetAudioInputs']();
}

export function GetAudioOutputs() {
  return window['go']['main']['App']['GetAudioOutputs']();
}

export function GetSkredVersion() {
  return window['go']['main']['App']['GetSkredVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SendSkodeCommand(arg1) {
  return window['go']['main']['App']['SendSkodeCommand'](arg1);
}

export function SetDelayParams(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetDelayParams'](arg1, arg2, arg3);
}

export function SetInputVolume(arg1) {
  return window['go']['main']['App']['SetInputVolume'](arg1);
}

export function StartDelayEngine(arg1, arg2) {
  return window['go']['main']['App']['StartDelayEngine'](arg1, arg2);
}

export function StopDelayEngine() {
  return window['go']['main']['App']['StopDelayEngine']();
}

export function ToggleFreeze(arg1) {
  return window['go']['main']['App']['ToggleFreeze'](arg1);
}
