// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChangeAudioDevice(arg1:number,arg2:number):Promise<string>;

export function GetAudioInputs():Promise<Array<main.Device>>;

export function GetAudioOutputs():Promise<Array<main.Device>>;

export function GetSkredParameters():Promise<string>;

export function GetSkredVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LoadConfig():Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function RefreshAudioDevices():Promise<void>;

export function SaveConfig(arg1:string):Promise<void>;

export function SendSkodeCommand(arg1:string):Promise<string>;

export function SetDelayParams(arg1:number,arg2:number,arg3:number):Promise<string>;

export function SetInputVolume(arg1:number):Promise<string>;

export function StartDelayEngine(arg1:number,arg2:number):Promise<string>;

export function StopDelayEngine():Promise<void>;

export function ToggleFreeze(arg1:boolean):Promise<void>;
